version: '2'
services:
  unity-idm:
    environment:
      HOST: unity-idm:2443
    image: docker.clarin.eu/unity-idm:1.1.0
    networks:
      idm_demo_network:
        aliases:
          - idp
    ports:
      - "2443:2443"
      - "10000:10000"
      - "10443:10443"
      - "9000:22"
    volumes:
      - unity_idm_data:/opt/unity/data:rw
      - saml_metadata:/data/metadata:rw

  shibboleth-sp:
    image: shibboleth/sp-demo:1.0.0
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - saml_metadata:/data/metadata:rw
    networks:
      idm_demo_network:
        aliases:
          - sp

  owncloud:
    environment:
      DATABASE_USER: owncloud
      DATABASE_NAME: owncloud_db
      OWNCLOUD_ADMIN: admin
      LDAP_HOST: unity-idm
      LDAP_PORT: 10000
      LDAP_USER_DN: uid=admin,ou=system
      LDAP_BASE_DN: ou=system
    image: docker.clarin.eu/owncloud:1.0.0
    networks:
      - idm_demo_network
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - owncloud_mysql_data:/var/lib/mysql/:rw
      #- owncloud_data:/var/www/html/:rw
      - owncloud_initialisation:/opt/initialisation/:rw
      - /Users/wilelb/idm_demo_secrets:/opt/.secrets:rw
      - /Users/wilelb/Code/work/clarin/git/owncloud/debug/owncloud/apps/user_ldap/lib:/var/www/html/apps/user_ldap/lib:rw

  website:
    command: |
      -ecx "dumb-init --single-child httpd -D FOREGROUND"
    entrypoint: /bin/sh
    depends_on:
      - mariadb
    image: "docker.clarin.eu/alpine-apache-drupal:0.8.2-0-g4112bc7"
    networks:
      - idm_demo_network
    ports:
      - "82:80"
      - "445:443"
    tmpfs:
      - "/tmp/:rw,noatime,nodev,noexec,mode=1777"
      - "/run/apache2/:rw,gid=101,mode=700,noatime,nodev,noexec,uid=100"
    read_only: true
    user: "100:82"
    volumes:
      - "website_httpd_htdocs:/var/www/localhost/htdocs/:rw"
      - "website_httpd_dynamic_cfg:/var/www/dynamic_cfg/:ro"
      - "website_httpd_certstore:/var/www/TLS_key_store/:ro"
    working_dir: "/var/www/localhost/htdocs/"

  mariadb:
    environment:
      MYSQL_DATABASE:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
    networks:
      - idm_demo_network
    image: "mariadb:10.1.16"
    tmpfs: "/tmp/:rw,noatime,nodev,noexec,mode=1777"
    tmpfs: "/run/:rw,noatime,nodev,noexec,mode=700"
    tmpfs: "/run/mysqld/:rw,gid=999,mode=700,noatime,nodev,noexec,uid=999"
    volumes:
      - "var_mariadb:/var/lib/mysql/:rw"
    working_dir: "/var/lib/mysql/"

volumes:
  owncloud_mysql_data:
    external: false
  owncloud_data:
    external: false
  owncloud_initialisation:
    external: false
  unity_idm_data:
    external: false
  saml_metadata:
    external: false
  website_httpd_dynamic_cfg:
    external: false
  website_httpd_htdocs:
    external: false
  website_httpd_certstore: #Managed via initialiser
    external: true
  var_mariadb:
    external: false

networks:
  idm_demo_network:
